# Generated by Django 4.2.3 on 2024-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('image1', models.ImageField(blank=True, upload_to='propert/')),
                ('image2', models.ImageField(blank=True, upload_to='propert/')),
                ('image3', models.ImageField(blank=True, upload_to='propert/')),
                ('image4', models.ImageField(blank=True, upload_to='propert/')),
                ('type', models.CharField(choices=[('House', 'HOUSE'), ('Flat', 'FLAT'), ('Shop', 'SHOP')], default=None, max_length=5)),
                ('purpose', models.CharField(choices=[('Sale', 'SALE'), ('Rent', 'RENT')], default=None, max_length=4)),
                ('price', models.CharField(max_length=10)),
                ('describ', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
